import 'server-only';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { PostsProvider } from '@/providers/PostsProvider';
import { LayoutProps } from '@/types/app';
import { getPosts } from './(posts)/_actions';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

// action fetch data -> provider -> state

export default async function RootLayout({ children }: LayoutProps) {
	const posts = await getPosts();

	return (
		<html lang="en">
			<body className={inter.className}>
				<PostsProvider initialPosts={posts}>{children}</PostsProvider>
			</body>
		</html>
	);
}
